### ISSUE TITLE
motorRecord can't be turned off in config

### ISSUE THREAD

**Issue by kivel** [paulscherrerinstitute/ecmccfg#152]
motorRecord is instantiated even when turned off
```yaml
epics:
  motorRecord:
    enable: false
```
`dbl motor` result for an IOC running v8_RC1
```bash
n4101> dbl motor
n4101:M1
n4101:M1_int
```
